export const AGREGAR_HEROE = "AGREGAR_HEROE";
export const AGREGAR_HEROE_EXITO = "AGREGAR_HEROE_EXITO";
export const AGREGAR_HEROE_ERROR = "AGREGAR_HEROE_ERROR";

export const COMENZAR_DESCARGA_HEROES = "COMENZAR_DESCARGA_HEROES";
export const DESCARGA_HEROES_EXITO = "DESCARGA_HEROES_EXITO";
export const DESCARGA_HEROES_ERROR = "DESCARGA_HEROES_ERROR";

export const OBTENER_ELIMINAR_HEROE = "OBTENER_ELIMINAR_HEROE";
export const HEROE_ELIMINADO_EXITO = "HEROE_ELIMINADO_EXITO";
export const COMENZAR_ELIMINAR_HEROE = "COMENZAR_ELIMINAR_HEROE";
